name: Check

on: [push, pull_request]

jobs:
  build:
    name: Check and lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        pip install requests

    - name: Check
      run: poetry run python -m check
    
- name: switching from HTTPS to SSH
  run: git remote set-url origin ${{ secrets.ssh }}
- name: check for changes
  run: git status
- name: stage changed files
  run: git add .
- name: commit changed files
  run: git commit -m "Auto updating TODO.txt"
- name: fetch from master
  run: git fetch origin master
- name: push code to master
  run: git push origin HEAD:master
